#############################################################################
# Makefile for building: Car.app/Contents/MacOS/Car
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  Car.pro
# Template: app
# Command: /Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/qmake -o Makefile Car.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers -I../../Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Headers -I../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang -F/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib
QMAKE         = /Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Car1.0.0
DISTDIR = /Users/ekin/Documents/gruppe7/.tmp/Car1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		car.cpp \
		map.cpp \
		mainwindow.cpp \
		selectgameobjectdialog.cpp \
		tree.cpp qrc_resources.cpp \
		moc_car.cpp \
		moc_mainwindow.cpp \
		moc_selectgameobjectdialog.cpp \
		moc_tree.cpp
OBJECTS       = main.o \
		car.o \
		map.o \
		mainwindow.o \
		selectgameobjectdialog.o \
		tree.o \
		qrc_resources.o \
		moc_car.o \
		moc_mainwindow.o \
		moc_selectgameobjectdialog.o \
		moc_tree.o
DIST          = ../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/qdevice.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/unix.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/mac.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/macx.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/qconfig.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/resources.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/moc.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/uic.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/lex.prf \
		Car.pro car.h \
		map.h \
		mainwindow.h \
		selectgameobjectdialog.h \
		tree.h main.cpp \
		car.cpp \
		map.cpp \
		mainwindow.cpp \
		selectgameobjectdialog.cpp \
		tree.cpp
QMAKE_TARGET  = Car
DESTDIR       = 
TARGET        = Car.app/Contents/MacOS/Car

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_car.h ui_mainwindow.h ui_selectgameobjectdialog.h $(OBJECTS)  
	@test -d Car.app/Contents/MacOS/ || mkdir -p Car.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Car.pro ../../Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/qdevice.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/unix.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/mac.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/macx.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/qconfig.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/resources.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/moc.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/uic.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/lex.prf \
		Car.pro \
		resources.qrc \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Car.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/qdevice.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/device_config.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/unix.conf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/mac.conf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/macx.conf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/sanitize.conf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang.conf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/qconfig.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/toolchain.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_post.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qml_debug.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/mac.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/resources.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/moc.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/uic.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/qmake_use.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/file_copies.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/yacc.prf:
../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/lex.prf:
Car.pro:
resources.qrc:
../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Car.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

Car.app/Contents/PkgInfo: 
	@test -d Car.app/Contents || mkdir -p Car.app/Contents
	@$(DEL_FILE) Car.app/Contents/PkgInfo
	@echo "APPL????" > Car.app/Contents/PkgInfo
Car.app/Contents/Resources/empty.lproj: 
	@test -d Car.app/Contents/Resources || mkdir -p Car.app/Contents/Resources
	@touch Car.app/Contents/Resources/empty.lproj
	
Car.app/Contents/Info.plist: 
	@test -d Car.app/Contents || mkdir -p Car.app/Contents
	@$(DEL_FILE) Car.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Car,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.Car,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.10,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Car,g" -e "s,@LIBRARY@,Car,g" -e "s,\$${EXECUTABLE_NAME},Car,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang/Info.plist.app >Car.app/Contents/Info.plist

all: Makefile \
		Car.app/Contents/PkgInfo \
		Car.app/Contents/Resources/empty.lproj \
		Car.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents car.h map.h mainwindow.h selectgameobjectdialog.h tree.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp car.cpp map.cpp mainwindow.cpp selectgameobjectdialog.cpp tree.cpp $(DISTDIR)/
	$(COPY_FILE) --parents car.ui mainwindow.ui selectgameobjectdialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Car.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		../../Qt5.10.1/5.10.1/clang_64/bin/rcc \
		tree.png \
		map2.png \
		mercedes_forWind.png \
		background.png \
		redbull_forWind.png \
		ferrari_forWind.png \
		ferrari.png \
		mercedes.png \
		redbull.png
	/Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../../Qt5.10.1/5.10.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_car.cpp moc_mainwindow.cpp moc_selectgameobjectdialog.cpp moc_tree.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_car.cpp moc_mainwindow.cpp moc_selectgameobjectdialog.cpp moc_tree.cpp
moc_car.cpp: ../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		car.h \
		moc_predefs.h \
		../../Qt5.10.1/5.10.1/clang_64/bin/moc
	/Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang -I/Users/ekin/Documents/gruppe7 -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Headers -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib car.h -o moc_car.cpp

moc_mainwindow.cpp: ../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		mainwindow.h \
		moc_predefs.h \
		../../Qt5.10.1/5.10.1/clang_64/bin/moc
	/Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang -I/Users/ekin/Documents/gruppe7 -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Headers -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_selectgameobjectdialog.cpp: ../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		selectgameobjectdialog.h \
		moc_predefs.h \
		../../Qt5.10.1/5.10.1/clang_64/bin/moc
	/Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang -I/Users/ekin/Documents/gruppe7 -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Headers -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib selectgameobjectdialog.h -o moc_selectgameobjectdialog.cpp

moc_tree.cpp: ../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		tree.h \
		moc_predefs.h \
		../../Qt5.10.1/5.10.1/clang_64/bin/moc
	/Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang -I/Users/ekin/Documents/gruppe7 -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Headers -I/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/Users/ekin/Qt5.10.1/5.10.1/clang_64/lib tree.h -o moc_tree.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_car.h ui_mainwindow.h ui_selectgameobjectdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_car.h ui_mainwindow.h ui_selectgameobjectdialog.h
ui_car.h: car.ui \
		../../Qt5.10.1/5.10.1/clang_64/bin/uic
	/Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/uic car.ui -o ui_car.h

ui_mainwindow.h: mainwindow.ui \
		../../Qt5.10.1/5.10.1/clang_64/bin/uic
	/Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_selectgameobjectdialog.h: selectgameobjectdialog.ui \
		../../Qt5.10.1/5.10.1/clang_64/bin/uic
	/Users/ekin/Qt5.10.1/5.10.1/clang_64/bin/uic selectgameobjectdialog.ui -o ui_selectgameobjectdialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

car.o: car.cpp car.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/QtMath \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/qmath.h \
		mainwindow.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o car.o car.cpp

map.o: map.cpp map.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		car.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		tree.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		selectgameobjectdialog.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o map.o map.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_mainwindow.h \
		selectgameobjectdialog.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		map.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		car.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		tree.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

selectgameobjectdialog.o: selectgameobjectdialog.cpp selectgameobjectdialog.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_selectgameobjectdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selectgameobjectdialog.o selectgameobjectdialog.cpp

tree.o: tree.cpp tree.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tree.o tree.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_car.o: moc_car.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_car.o moc_car.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_selectgameobjectdialog.o: moc_selectgameobjectdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selectgameobjectdialog.o moc_selectgameobjectdialog.cpp

moc_tree.o: moc_tree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tree.o moc_tree.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

